apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: 24ws-ase-pr-inso-02
type: Opaque
data:
  POSTGRES_PASSWORD: "OTA2N2M0MTQ1YTAyY2E2MGUxOGZmNjZhMTMzZDIyNDMxZDRkMjEwNjExYmMzYTRlM2QwZDRmMTA2NTA1OTliZA=="
stringData:
  POSTGRES_USER: barter
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: 24ws-ase-pr-inso-02
type: Opaque
data:
  RABBITMQ_DEFAULT_PASS: "MDIzZWMzNjEwYTI2Yzg1Y2MyMzk5NWJlYTZjNTc2MmI1YjQ5MzBjMmQyYjhjODJlYzRmYWI1NTczYTNmZjE4OQ=="
stringData:
  RABBITMQ_DEFAULT_USER: "barter"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
