apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: 24ws-ase-pr-inso-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgis/postgis:17-3.5-alpine
        resources:
          requests:
            memory: "128Mi"
            cpu: "10m"
            ephemeral-storage: "100Mi"
          limits:
            memory: "400Mi"
            cpu: "350m"
            ephemeral-storage: "250Mi"
        envFrom:
          - secretRef:
              name: postgres-secret
          - configMapRef:
              name: postgres-config
        # - name: POSTGRES_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: postgres-secret
        #       key: postgres-password
        ports:
        - containerPort: 5432
        # volumeMounts:
        # - name: postgres-storage
        #   mountPath: /var/lib/postgresql/data
      # volumes:
      # - name: postgres-storage
      #   persistentVolumeClaim:
      #     claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: 24ws-ase-pr-inso-02
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
